spring:
  application:
#    项目名称
    name: enterprise-cloud

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/miyano?serverTimezone=UTC
#    username: root
#    password: miyano12138

  resources:
#    静态资源位置
    static-locations: classpath:/static/

  devtools:
    restart:
#      启动热部署
      enabled: true
  mvc:
    view:
#      .html 后缀
      suffix: .html
server:
#  默认端口
  port: 8080
