spring:
  application:
    name: enterprisecloud

  resources:
    static-locations: classpath:/static/

  devtools:
    restart:
      enabled: true

  mvc:
    view:
      suffix: .html

server:
  port: 8080
