spring:
  application:
    #    项目名称
    name: enterprise-cloud
  devtools:
    restart:
      #      启动热部署
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/miyano?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: miyano12138

mybatis:
  type-aliases-package: com.example.mybatis.dao
  mapper-locations: classpath:mapper/*.xml


server:
  #  默认端口
  port: 8080


